"""Utility to split data generated by auto-labeler into train and val sets."""
import os
import subprocess

from sklearn.model_selection import train_test_split

dataset_path = "../../training_data"
input_data_path = os.path.join(dataset_path, "raw_data")
images_folder = os.path.join(input_data_path, "images")
labels_folder = os.path.join(input_data_path, "labels")
output_images_folder = os.path.join(dataset_path, "images")
output_labels_folder = os.path.join(dataset_path, "labels")

os.makedirs(output_images_folder, exist_ok=True)
os.makedirs(output_labels_folder, exist_ok=True)

images = []
for file in os.listdir(images_folder):
    path = os.path.join(images_folder, file)
    if os.path.isfile(path): images.append(file)

train_images, val_images = train_test_split(images, test_size=0.2, random_state=42)

print(f"Train images: {len(train_images)}")
print(f"Val images: {len(val_images)}")

os.makedirs(os.path.join(output_images_folder, "train"), exist_ok=True)
os.makedirs(os.path.join(output_images_folder, "val"), exist_ok=True)
os.makedirs(os.path.join(output_labels_folder, "train"), exist_ok=True)
os.makedirs(os.path.join(output_labels_folder, "val"), exist_ok=True)

for image in train_images:
    path_to_image = os.path.join(images_folder, image)
    label_file = image.replace(".jpg", ".txt")
    path_to_label = os.path.join(labels_folder, label_file)

    subprocess.run(["cp", path_to_image, os.path.join(output_images_folder, "train", image)])
    print(f"Moved {image} to train folder")
    subprocess.run(["cp", path_to_label, os.path.join(output_labels_folder, "train", label_file)])
    print(f"Moved {label_file} to train folder")

for image in val_images:
    path_to_image = os.path.join(images_folder, image)
    label_file = image.replace(".jpg", ".txt")
    path_to_label = os.path.join(labels_folder, label_file)

    subprocess.run(["cp", path_to_image, os.path.join(output_images_folder, "val", image)])
    print(f"Moved {image} to val folder")
    subprocess.run(["cp", path_to_label, os.path.join(output_labels_folder, "val", label_file)])
    print(f"Moved {label_file} to val folder")

subprocess.run(["cp", os.path.join(labels_folder, "classes.txt"), os.path.join(output_labels_folder, "val", "classes.txt")])
subprocess.run(["cp", os.path.join(labels_folder, "classes.txt"), os.path.join(output_labels_folder, "train", "classes.txt")])


